title: Public Speaking Basics
tagline: Learn all about what makes a good public speaker w/ Chloe Condon!
description: >-
  In this course you’ll learn all about what makes a good public speaker, and
  how to apply those skills to your own presentations!
template:
  repo: public-speaking-basics-template
  name: public-speaking-basics2
  description: >-
    This is the repo for my public speaking basics course! Check it out on
    Learning Lab!
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: Meet your instructor
    description: 'Get details on the course, your instructor, etc!'
    event: issues.closed
    link: '{{ repoUrl }}/issues/1'
    actions:
      - type: createIssue
        title: Issue 2!
        body: issue-2.md
        action_id: issue2
      - type: respond
        issue: Welcome!
        with: comment1.md
        data:
          url: '%actions.issue2.data.html_url%'
